# 通用配置（这些配置是没有必要放到apollo去的固定配置[或者增加可读性的配置]，如果容易变动的配置，最好放到apollo里进行配置）

server:
  context-path: /c
  compression:
      enabled: true
      mime-types: application/json,application/xml,text/html,text/xml,text/plain
      min-response-size: 2048
  undertow:
    io-threads: 16
    worker-threads: 248
    buffer-size: 1024


spring:
  ### 项目基本信息
  application:
    name: "${server_name}"
  profiles:
    #### 只有设置active属性，才会在开发环境加载dev的配置，default：dev不会加载下方配置
    active: ${project.environment}

  ### http配置
  http:
    encoding:
      charset: UTF-8
      force: true

logging:
  config: "classpath:config/log4j2-${spring.profiles.active}.xml"


  ### jackson配置
  jackson:
    serialization:
      write_dates_as_timestamps: false
      fail_on_empty_beans: false
    deserialization:
      fail_on_unknown_properties: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

  ### freemarker配置
  freemarker:
    preferFileSystemAccess: true
    cache: true
    prefix: classpath:/templates
    suffix: .ftl
    content-type: text/html; charset=UTF-8
    # 这是一个map,注入到factory的settings中
    # settings:

  output:
    ansi:
      enabled: always

## 监控
info:
  app:
    name: "${server_name}"
    encoding: UTF-8

endpoints:
  actuator:
    enabled: true
management:
  security:
    enabled: false
  context-path: /_monitor

## spring cloud相关

ribbon:
  eureka:
   enabled: false

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

## 自定义配置

htonline:
  wrapper.enabled: true
  httpclient.enabled: false
  okhttp.enabled: true
  executor.enabled: true


# 不同环境的不同配置，也可以放在apollo，除了开发使用的特殊debug等配置，一般不建议放在这里
---
spring:
  profiles: dev

server:
  port: 80

debug: true

---
spring:
  profiles: test

---
spring:
  profiles: release

---
spring:
  profiles: product

