spring:
  application:
    name: course-web-server

course-service:
  ribbon:
    IsSecure: true
    SecurePort: 443
    listOfServers: https://apitk.huatu.com:443

ribbon:
  eureka:
   enabled: false

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true


debug:
  true
